version: '3.8'

services:
  # MySQL Service
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: db  # The database that will be created on startup
      MYSQL_USER: user     # A non-root MySQL user
      MYSQL_PASSWORD: 123  # Password for the non-root user
      MYSQL_ROOT_PASSWORD: root  # Password for the root user
    ports:
      - 3306:3306  # Exposes MySQL on your machine's port 3306
    expose:
      - 3306  # Exposes port to other containers in the same Docker network
    volumes:
      - my-db:/var/lib/mysql  # Persists MySQL data

  # Adminer Service
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080  # Exposes Adminer web interface on port 8080

# Define volumes
volumes:
  my-db:  # Persist data even when the container is stopped or removed
